[package]
name = "mc_protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.1"
anyhow = "1.0.56"
bytes = "1.1.0"
cfb8 = "0.8.1"
flate2 = "1.0.23"
hematite-nbt = "0.5.2"
log = "0.4.16"
uuid = "0.8.2"
